[reports]

    [reports.example1]
    type = "http"
    url = "http://example.com"
    method = "POST"
    payload = "{\"hello\": \"world\", \"field1\": \"{SERVICE_NAME} {TOPIC} {DESCRIPTION} {TYPE}\"}" # Optional
        [reports.example1.header] # Optional
        "Authorization" = "..."

    [reports.example2]
    type = "discord"
    url = "https://discord.com/api/webhooks/123/abc"
    content = "@everyone" # Optional
        [reports.example2.icons] # Optional
        "toilet" = "https://yt3.ggpht.com/a/AATXAJzg_11V_V_jb1dvFuDrI7RWadpt6DmUeFSyDQ=s900-c-k-c0xffffffff-no-rj-mo"